debug: False
robot_model: FrankaResearch3
robot_id: fr3_arm_1

x_pos: 5
y_pos: 5.21 #5.45
z_pos: 0.85
yaw: -1.57
spawn_delay: 15.0

workspace: ["prep_grill"]

use_sim: true

skill_weights:  #[skill weight, preference weight]
  HouseParty:
    manipulation: [1.0, 1.0]

  quality_check:
    manipulation: [1.0, 0.2]
    planning: [0.3, 0.5]