debug: true
use_sim: true

robot_model: Human
robot_id: host

x_pos: 0.0
y_pos: 0.0
yaw: 0
actor_type: WalkingActor
color: red
spawn_delay: 15.0

workspace: ["Prep_Table", "Garden", "Kitchen_Table", "Kitchen_Stove", "Grill_Table", "House", "Kitchen_sink", "Kitchen_shelves", "Drinks_Table"]

result_timeout: 120.0

skill_weights:  #[skill weight, preference weight]
  HouseParty:
    transport: [1.0, 0.1]
    manipulation: [0.9, 0.6]
    communication: [1.0, 0.8]
    openDoor: [1.0, 0.1]

  assembly:
    navigation: [0.1, 0.8]
    manipulation: [0.6, 0.2]
    planning: [0.3, 0.5]