debug: true

robot_model: Human
robot_id: host

x_pos: -0.19
y_pos: -6.76
yaw: 0
actor_type: WalkingActor

spawn_delay: 15.0

use_sim: true

result_timeout: 120.0

skill_weights:  #[skill weight, preference weight]
  delivery:
    navigation: [0.6, 0.1]
    manipulation: [0.2, 0.6]
    planning: [0.2, 0.3]

  assembly:
    navigation: [0.1, 0.8]
    manipulation: [0.6, 0.2]
    planning: [0.3, 0.5]