debug: False
robot_model: Tiago
robot_id: tiago_robot1

x_pos: 0.3
y_pos: 0.0
z_pos: 1.03
yaw: -3.14
spawn_delay: 15.0

use_sim: true

skill_weights:  #[skill weight, preference weight]
  HouseParty:
    transport: [0.7, 0.1]
    manipulation: [0.5, 0.6]
    communication: [0.2, 0.3]

  assembly:
    navigation: [0.1, 0.8]
    manipulation: [1.0, 0.2]
    planning: [0.3, 0.5]