#debug: True
task: configs/goals/default_graph.json
team_size: 3
top_k: 2
optimizeMode: skill

world_name: backyard

mock: False  # True = ROS-agnostic test, False = use ROS/MoveIt
use_sim: True          # True = simulation mode, False = real robot
