#debug: True
task: configs/goals/barbecue.json #configs/goals/default_graph.json
optimizeMode: skill

world_name: backyard

use_sim: True          # True = simulation mode, False = real robot

team_size: 4
top_k: 2

agents:
  - fr3_arm_1
  - tiago_robot_1
  - fr3_arm_2
  - human_host


supervisor: fr3_arm_1
