robot_model: Pepper
robot_id: pepper_mobile_1
#skills = ["manipulation", "navigation", "show_visual_media", "transport_objects"]
skill_weights:  #[skill weight, preference weight]
  delivery:
    navigation: [0.6, 0.1]
    manipulation: [0.2, 0.6]
    planning: [0.2, 0.3]

  assembly:
    navigation: [0.1, 0.8]
    manipulation: [0.6, 0.2]
    planning: [0.3, 0.5]