<?xml version="1.0"?>
<package format="3">
  <name>pioneer3at_adapters</name>
  <version>1.0.0</version>
  <description>Pioneer 3-AT description and Gazebo Fortress integration for ROS 2 Humble.</description>

  <maintainer email="leticia.berto@manchester.ac.uk">Leticia Berto</maintainer>
  <license>BSD</license>

  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
